name: Publish on Modrinth
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Run unit tests + Build (shadow) JAR file + Publish on Modrinth
      - name: Build and publish on Modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          MODRINTH_PROJECT_ID: ${{ vars.MODRINTH_PROJECT_ID }}
        run: ./gradlew build modrinth

      - name: List output files
        if: always()
        run: |
          echo "ðŸ“‚ Contents of the ./build/libs folder:"
          ls -R ./build/libs/

      - name: Summary of published version
        if: success()
        run: |
          VERSION=$(grep '^projectVersion=' gradle.properties | cut -d '=' -f2)
          GAME_VERSIONS=$(grep '^supportedGameVersions=' gradle.properties | cut -d '=' -f2)
          TYPE=$(grep '^versionType=' gradle.properties | cut -d '=' -f2)
          LOADERS=$(grep '^compatibleLoaders=' gradle.properties | cut -d '=' -f2)
          
          echo "ðŸš€ Plugin successfully published on Modrinth !"
          echo "âœ… Project version: $VERSION"
          echo "âœ… Supported Minecraft version(s): $GAME_VERSIONS"
          echo "âœ… Version type: $TYPE"
          echo "âœ… Compatible loaders: $LOADERS"
          
          echo "projectVersion=$VERSION" >> $GITHUB_ENV

      # Create GIT tag if the release was successful
      - name: Create GIT tag
        if: success()
        run: |
          git tag v${{ env.projectVersion }}
          git push origin v${{ env.projectVersion }}
